### ISSUE TITLE
Cant compile on rpi4

### ISSUE THREAD

**Issue by CarloCattano** [benkuper/LeGrandMechantLoop#8]
**Environment**
 - OS: patchboxOS 32bit 
 -  5.10.63-v7l+ armv7l

Getting some errors after making sure JUCE files are present and custom modules from LeGrandMechantLoop too ,
cd  ~/LeGrandMechantLoop/Builds/Raspberry
make 

[dump.txt](https://github.com/benkuper/LeGrandMechantLoop/files/7274270/dump.txt)

Errors with members and classes etc 

Am I using a wrong version of JUCE ? 

Thrilled to try this on my pi

**Comment by benkuper** [comment]
I guess you're not using my fork of JUCE but the official JUCE repo, right ?
You need to use the develop-local branch of this fork : https://github.com/benkuper/JUCE/tree/develop-local

**Comment by CarloCattano** [comment]
Thanks a lot, will do so

**Comment by CarloCattano** [comment]
weird , now Im getting some missing stuff from vst libs , I added a missing vsttypes.h header that I didn't have , but all the others are unfamiliar to me . Now I get 
```
/home/patch/vstsdk2.4/pluginterfaces/vst2.x/vsttypes.h:19:10: fatal error: pluginterfaces/base/fstrdefs.h: No such file or directory
 #include "pluginterfaces/base/fstrdefs.h"
``` 

Im using the juce develop-local, built projucer  and cloned recursively 

I get the vst2sdk from :
```
wget https://archive.org/download/VST2SDK/vst_sdk2_4_rev2.zip
```

**Comment by benkuper** [comment]
The VST2 files are included in the repo and are in the "External" folder, you shouldn't need more than that.

**Comment by CarloCattano** [comment]
Alright . Turned out I wrongly assumed that vst sdk folder should have been as posted before . Cloned the official vst3sdk repo, copied the contents of pluginterfaces from the vst2 to the vst3 pluginterfaces one and worked

**Comment by benkuper** [comment]
VST3 SDK should be handled by JUCE, the CUSTOM_VST3 option is disabled in the Projucer for this project

**Comment by CarloCattano** [comment]
Got it working . You dont include vsttypes.h in your /External/vst so I was getting confused 

Had to manually add the libs to my /usr path and use     LDFLAGS=-latomic  in order to link succesfully on the pi4 runnin a 32bit OS

**Comment by benkuper** [comment]
good to know, I don't think this is what I do in the cross-compilation on github actions, but actually I'm not the one who did it so... :)

**Comment by CarloCattano** [comment]
All good. Is such a long time i look for a midi looper and this is the perfect tool!
